import React from 'react';
import LegalLayout, { H, P, LI } from './LegalLayout';

export default function Privacy() {
  return (
    <LegalLayout title="Privacy Policy" updated="19 July 2026">
      <P>
        GameFit ("we", "us") is a gamified fitness application operated from the United Arab
        Emirates. This policy explains what personal data we collect, why, and the rights you
        have over it. It is written to comply with the UAE Personal Data Protection Law
        (Federal Decree-Law No. 45 of 2021, "PDPL") and the EU General Data Protection
        Regulation ("GDPR") where applicable.
      </P>

      <H>What we collect</H>
      <ul className="space-y-1.5">
        <LI><strong>Account data</strong> — email address, name, and password (stored as a secure hash), or your Google account identity if you sign in with Google.</LI>
        <LI><strong>Profile data you provide</strong> — age, height, weight, calculated BMI, fitness goal, experience level, weekly training target, and avatar preferences.</LI>
        <LI><strong>Activity data</strong> — workouts you log (type, duration, intensity, notes), meals you log, and the XP, coins, streaks and badges derived from them.</LI>
        <LI><strong>AI coaching content</strong> — messages you send to Coach G and, if you use the premium meal-photo feature, the photos you submit for analysis.</LI>
        <LI><strong>Connected services (optional)</strong> — if you connect Strava, we store access tokens and basic athlete info to sync your activities. You can disconnect at any time.</LI>
        <LI><strong>Payment status</strong> — whether you have an active Premium subscription and your Stripe customer/subscription identifiers. We never see or store your card number.</LI>
        <LI><strong>Usage and diagnostics</strong> — app events (e.g. "workout logged") and crash reports, used to improve the product.</LI>
      </ul>

      <H>Why we process it</H>
      <P>
        To operate your account and the game economy; to personalise AI coaching to your stated
        profile; to process subscription payments; to show leaderboards (only your display name,
        rank, level, XP and avatar appearance are visible to others — never your email, body
        metrics or private data); to keep the service secure; and to improve GameFit. We do not
        sell your personal data.
      </P>

      <H>AI processing</H>
      <P>
        Coach G responses are generated by Anthropic's Claude models. Your questions, relevant
        profile fields (age, height, weight, BMI, goal, experience), and submitted meal photos
        are sent to Anthropic to generate a response. Coach G provides general fitness guidance
        only and is not a medical service.
      </P>

      <H>Our processors</H>
      <ul className="space-y-1.5">
        <LI><strong>Supabase</strong> — database, authentication and file storage.</LI>
        <LI><strong>Vercel</strong> — application hosting and delivery.</LI>
        <LI><strong>Stripe</strong> — subscription payments.</LI>
        <LI><strong>Anthropic</strong> — AI coaching responses.</LI>
        <LI><strong>PostHog</strong> — product analytics (event data).</LI>
        <LI><strong>Sentry</strong> — error and crash reporting.</LI>
        <LI><strong>Strava</strong> — only if you choose to connect it.</LI>
        <LI><strong>Resend</strong> — transactional email (e.g. subscription notices).</LI>
      </ul>

      <H>Retention and deletion</H>
      <P>
        We keep your data while your account exists. You can permanently delete your account at
        any time in the app (Profile → Delete Account) or by following the steps at
        gamefit.online/delete-account. Deletion removes your profile, workouts, meals, coaching
        logs, photos and rewards, and cancels any active subscription. Some payment records are
        retained by Stripe as required by financial regulations.
      </P>

      <H>Your rights</H>
      <P>
        Under the PDPL and GDPR you may request access to, correction of, or erasure of your
        personal data, object to or restrict processing, and request portability. Write to
        support@gamefit.online — we respond within 30 days.
      </P>

      <H>Age requirement</H>
      <P>
        GameFit is for users aged 16 and older. We do not knowingly collect data from anyone
        under 16; such accounts are deleted when identified. Users under 18 receive
        age-appropriate, conservative AI coaching.
      </P>

      <H>Security</H>
      <P>
        Data is encrypted in transit (TLS) and at rest. Access is controlled by row-level
        security so each user can only reach their own records; game progression is computed
        server-side. Strava tokens are stored in a table no client can read.
      </P>

      <H>International transfers</H>
      <P>
        Our processors may store data in the EU or US under their standard contractual
        safeguards. By using GameFit you consent to these transfers as permitted by the PDPL.
      </P>

      <H>Changes</H>
      <P>
        We will update this page and change the date above when this policy changes. Material
        changes are announced in the app.
      </P>
    </LegalLayout>
  );
}
